fn_brace_style = "SameLineWhere"
fn_args_density = "Compressed"
fn_args_layout = "Visual"
fn_arg_intent = "Tabbed"
format_strings = false
reorder_imports = true
reorder_imported_names = true
report_todo = "Always"
report_fixme = "Always"
wrap_comments = true
normalize_comments = true
use_try_shorthand = true
max_width = 110
